ipath = ['-I' '/usr/local/include/'];
deps = ['./ChemotaxisSimulation/ChemotaxisSimulation/concentration_grid.cpp ',...
    './ChemotaxisSimulation/ChemotaxisSimulation/ecoli_bacterium.cpp ', ...
    './ChemotaxisSimulation/ChemotaxisSimulation/geometry.cpp ', ...
    './ChemotaxisSimulation/ChemotaxisSimulation/random.cpp ', ...
    './ChemotaxisSimulation/ChemotaxisSimulation/simulation_wrapper.cpp ' ]

mex(ipath, 'mx_alloc_simulation.cpp','simulation_wrapper.cpp', 'concentration_grid.cpp', 'ecoli_bacterium.cpp', 'geometry.cpp', ...
           'random.cpp' )